name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  wf-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FitSync.sln

      - name: Build the solution
        run: dotnet build FitSync.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test FitSync.UnitTests/FitSync.UnitTests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"