
name: CI/CD Workflow

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch (including feature branches)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FitSync.sln

      - name: Build Project
        run: dotnet build FitSync.sln --configuration Release

  create-pr:
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Pull Request"
          body: "This pull request was created automatically."
          base: main
          branch: ${{ github.head_ref || github.ref_name }}

  run-tests:
    runs-on: ubuntu-latest
    needs: create-pr  # This job depends on the create-pr job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Unit Tests
        run: dotnet test FitSync.UnitTests/FitSync.UnitTests.csproj --no-build --verbosity normal
